export const tagColors = {
  Fintech: "bg-blue-100 text-blue-600",
  "Payment gateway": "bg-purple-100 text-purple-600",
  Technology: "bg-gray-100 text-gray-600",
  AI: "bg-red-100 text-red-600",
  "E-commerce": "bg-yellow-100 text-yellow-600",
  Telecom: "bg-green-100 text-green-600",
  Banking: "bg-indigo-100 text-indigo-600",
  Aviation: "bg-teal-100 text-teal-600",
};

export const companiesData = [
  {
    id: 1,
    name: "eSewa",
    icon: "/jobs/sample.png",
    description:
      "eSewa is Nepal's leading digital payment platform offering services like mobile top-up, utility bill payments, and online shopping.",
    tags: ["Fintech", "Payment gateway"],
    jobs: [19],
    industry: "Fintech",
    companySize: "251-500",
    location: "Kathmandu, Nepal",
    founded: 2009,
    employee: 300,
  },
  {
    id: 2,
    name: "Khalti",
    icon: "/jobs/sample.png",
    description:
      "Khalti is a digital wallet providing payment solutions for various services including bills payment, ticketing, and online shopping.",
    tags: ["Fintech", "Payment gateway"],
    jobs: [10, 20],
    industry: "Fintech",
    companySize: "151-250",
    location: "Lalitpur, Nepal",
    founded: 2017,
    employee: 200,
  },
  {
    id: 3,
    name: "CloudFactory",
    icon: "/jobs/sample.png",
    description:
      "CloudFactory provides workforce solutions for AI and machine learning data processing, helping businesses scale their operations.",
    tags: ["Technology", "AI"],
    jobs: [1, 6, 24],
    industry: "Technology",
    companySize: "501-1000",
    location: "Kathmandu, Nepal",
    founded: 2008,
    employee: 800,
  },
  {
    id: 4,
    name: "F1Soft International",
    icon: "/jobs/sample.png",
    description:
      "Developer of popular digital financial platforms including eSewa and other banking solutions for Nepal's financial sector.",
    tags: ["Fintech", "Technology"],
    jobs: [8, 22, 32],
    industry: "Fintech",
    companySize: "251-500",
    location: "Kathmandu, Nepal",
    founded: 2004,
    employee: 450,
  },
  {
    id: 5,
    name: "Daraz Nepal",
    icon: "/jobs/sample.png",
    description:
      "Nepal's largest online marketplace offering products across various categories with delivery across the country.",
    tags: ["E-commerce"],
    jobs: [7, 29],
    industry: "E-commerce",
    companySize: "251-500",
    location: "Lalitpur, Nepal",
    founded: 2014,
    employee: 400,
  },
  {
    id: 6,
    name: "Nepal Telecom",
    icon: "/jobs/sample.png",
    description:
      "The largest telecommunications service provider in Nepal offering mobile, internet, and other communication services.",
    tags: ["Telecom"],
    jobs: [15, 28],
    industry: "Telecom",
    companySize: "1000-above",
    location: "Kathmandu, Nepal",
    founded: 2004,
    employee: 5000,
  },
  {
    id: 7,
    name: "Nabil Bank",
    icon: "/jobs/sample.png",
    description:
      "One of Nepal's leading commercial banks providing a wide range of banking and financial services.",
    tags: ["Banking"],
    jobs: [11, 30],
    industry: "Banking",
    companySize: "501-1000",
    location: "Kathmandu, Nepal",
    founded: 1984,
    employee: 900,
  },
  {
    id: 8,
    name: "Yeti Airlines",
    icon: "/jobs/sample.png",
    description:
      "A premier domestic airline in Nepal operating flights to various destinations across the country.",
    tags: ["Aviation"],
    jobs: [12],
    industry: "Aviation",
    companySize: "501-1000",
    location: "Pokhara, Nepal",
    founded: 1998,
    employee: 700,
  },
  {
    id: 9,
    name: "Code Himalaya",
    icon: "/jobs/sample.png",
    description:
      "Software development company specializing in custom software solutions for businesses.",
    tags: ["Technology"],
    jobs: [4, 18, 31],
    industry: "Technology",
    companySize: "1-50",
    location: "Bhaktapur, Nepal",
    founded: 2020,
    employee: 25,
  },
  {
    id: 10,
    name: "Leapfrog Technology",
    icon: "/jobs/sample.png",
    description:
      "Digital product development company building innovative software solutions for global clients.",
    tags: ["Technology"],
    jobs: [3, 16, 23],
    industry: "Technology",
    companySize: "51-150",
    location: "Lalitpur, Nepal",
    founded: 2010,
    employee: 130,
  },
  {
    id: 11,
    name: "Cotiviti Nepal",
    icon: "/jobs/sample.png",
    description:
      "Healthcare analytics and payment accuracy solutions provider helping healthcare payers manage costs.",
    tags: ["Healthcare"],
    jobs: [14],
    industry: "Healthcare",
    companySize: "501-1000",
    location: "Kathmandu, Nepal",
    founded: 2004,
    employee: 600,
  },
  {
    id: 12,
    name: "Foodmario",
    icon: "/jobs/sample.png",
    description:
      "Online food delivery platform connecting restaurants with customers across major cities in Nepal.",
    tags: ["Food & Beverage"],
    jobs: [9],
    industry: "Food & Beverage",
    companySize: "51-150",
    location: "Kathmandu, Nepal",
    founded: 2017,
    employee: 80,
  },
  {
    id: 13,
    name: "Fusemachines Nepal",
    icon: "/jobs/sample.png",
    description:
      "AI solutions provider offering artificial intelligence and machine learning services to global clients.",
    tags: ["Technology", "AI"],
    jobs: [2, 13, 25],
    industry: "Technology",
    companySize: "151-250",
    location: "Kathmandu, Nepal",
    founded: 2013,
    employee: 200,
  },
  {
    id: 14,
    name: "EB Pearls",
    icon: "/jobs/sample.png",
    description:
      "Digital agency specializing in web and mobile app development for clients worldwide.",
    tags: ["Technology"],
    jobs: [5, 17, 26],
    industry: "Technology",
    companySize: "151-250",
    location: "Lalitpur, Nepal",
    founded: 2005,
    employee: 180,
  },
  {
    id: 15,
    name: "Deerwalk",
    icon: "/jobs/sample.png",
    description:
      "Healthcare analytics and software development company with expertise in data-driven solutions.",
    tags: ["Technology", "Healthcare"],
    jobs: [21],
    industry: "Technology",
    companySize: "151-250",
    location: "Kathmandu, Nepal",
    founded: 2010,
    employee: 220,
  },
];

export const staticIndustryLabels = [
  "Advertising",
  "Business Service",
  "Blockchain",
  "Cloud",
  "Consumer Tech",
  "Education",
  "Fintech",
  "Gaming",
  "Food & Beverage",
  "Healthcare",
  "Hosting",
];

export const staticCompanySizeLabels = [
  "1-50",
  "51-150",
  "151-250",
  "251-500",
  "501-1000",
  "1000-above",
];
export const staticLocationLabels = [
  "Kathmandu, Nepal",
  "Lalitpur, Nepal",
  "Bhaktapur, Nepal",
  "Pokhara, Nepal",
  "Biratnagar, Nepal",
  "Birgunj, Nepal",
];
